# Generated by Django 5.2.16 on 2026-07-29 15:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('document', 'Document'), ('archive', 'Archive'), ('code', 'Code'), ('link', 'Link'), ('other', 'Other')], default='text', max_length=12)),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=vault.models.vault_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=vault.models.vault_thumbnail_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_deleted', 'created_at'], name='vault_user_del_created_idx'), models.Index(fields=['user', 'is_favorite', 'created_at'], name='vault_user_fav_created_idx'), models.Index(fields=['user', 'file_hash'], name='vault_user_filehash_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vault_search_vector_gin')],
            },
        ),
    ]
